actor_path:
  value: rsc/actor_20000.txt
  dtype: string

estimator_path:
  value: rsc/estimator_20000.txt
  dtype: string

obs_mean_path:
  value: rsc/obs_mean20000.csv
  dtype: string

obs_var_path:
  value: rsc/obs_var20000.csv
  dtype: string

eout_mean_path:
  value: rsc/eout_mean20000.csv
  dtype: string

eout_var_path:
  value: rsc/eout_var20000.csv
  dtype: string