real_robot:
  value: false
  dtype: bool

actor_path:
  value: rsc/actor_60000.txt
  dtype: string

estimator_path:
  value: rsc/estimator_60000.txt
  dtype: string

obs_mean_path:
  value: rsc/obs_mean60000.csv
  dtype: string

obs_var_path:
  value: rsc/obs_var60000.csv
  dtype: string

eout_mean_path:
  value: rsc/eout_mean60000.csv
  dtype: string

eout_var_path:
  value: rsc/eout_var60000.csv
  dtype: string