actor_path:
  value: rsc/actor_29500.pt
  dtype: string

estimator_path:
  value: rsc/estimator_29500.pt
  dtype: string

obs_mean_path:
  value: rsc/obs_mean29500.csv
  dtype: string

obs_var_path:
  value: rsc/obs_mean29500.csv
  dtype: string

eout_mean_path:
  value: rsc/eout_mean29500.csv
  dtype: string

eout_var_path:
  value: rsc/eout_mean29500.csv
  dtype: string